personal:
  full_name: Farley Knight
  email: farleyknight@gmail.com
  description: Ruby on Rails web developer working for <a href='http://patdeegan.com'>PDA</a>, a mental health startup.

wordpress:
  url: "farleyknight.wordpress.com"

twitter:
  username: farleyknight

github:
  username: farleyknight
